language: php

sudo: required
dist: trusty
php:
  - 7.4

before_install:
  - composer self-update
  - composer clear-cache
  - printf "\n" | pecl install redis
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer install
  - phpunit --configuration tests/unittests/phpunit.xml tests/unittests

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>="
  secret_access_key:
    secure: "Encypted <secret-access-key>="
  region: "eu-central-1"
  app: "OldiesButGoldiesApp"
  env: "OldiesButGoldiesApp-environment"
  bucket_name: "elasticbeanstalk-eu-central-1-201717832248"