anguage: php

sudo: required
dist: trusty
php:
  - 7.4

before_install:
  - composer self-update
  - composer clear-cache
  - composer update --no-interaction --no-ansi --no-suggest --optimize-autoloader --prefer-stable

before_script:
  - pecl install redis

script:
  - composer install
  - phpunit --configuration tests/unittests/phpunit.xml tests/unittests