version: '3'
services:
  oldies_app_postgres:
    build: ./docker/postgres
    container_name: oldies_app_postgres
    image: oldies_app_postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "oldies_db_user"
      POSTGRES_DB: "oldies_api_db"
      POSTGRES_PASSWORD: "oldies_api_password"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  oldies_app_php_fpm:
    build: ./docker/php-fpm
    container_name: oldies_app_php_fpm
    restart: always
    image: oldies_app_php_fpm
    entrypoint: ["sh", "/usr/local/bin/init.sh", "php-fpm", "-F"]
    volumes:
      - .:/var/www/html
    links:
      - oldies_app_postgres
    depends_on:
      - oldies_app_postgres

  oldies_app_nginx:
    container_name: oldies_app_nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - oldies_app_php_fpm
    depends_on:
      - oldies_app_php_fpm

  oldies_app_redis:
    container_name: oldies_app_redis
    image: bitnami/redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "true"